version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:4000" # localhost:8000 maps to container:4000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - database_default

  database_default:
    image: postgres:15.7-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database-default:/var/lib/postgresql/data

volumes:
  database-default:
